---
title: slide_title
subtitle: ""
author: "Martin Frigaard"
institute: "Paradigm Data Group"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css:
      - default
      - css/styles.css
    lib_dir: libs
    seal: false
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
---

```{r meta, echo=FALSE}
library(metathis)
meta() |>
  meta_general(
    description = '{name}',
    generator = 'xaringan and remark.js'
  ) |>
  meta_name('github-repo' = 'paradigmdatagroup/{name}/') |>
  meta_social(
    title = '{name}',
    url = 'https://github.com/paradigmdatagroup/{name}/',
    og_type = 'website',
    og_author = 'Martin Frigaard'
  ) 
```

```{r setup, include=FALSE}
dateWritten <- format(Sys.Date(), format = '%B %d %Y')
today <- format(Sys.Date(), format = '%B %d %Y')
library(knitr)
library(rmarkdown)
library(fontawesome)
library(gtsummary)
options(
    htmltools.dir.version = FALSE,
    knitr.table.format = 'html',
    knitr.kable.NA = ''
)
knitr::opts_chunk$set(
    warning = FALSE,
    message = FALSE,
    fig.path = 'www/',
    fig.width = 7.252,
    fig.height = 4,
    comment = ' ',
    fig.retina = 3 # Better figure resolution
)
# knitr::opts_knit$set(root.dir = 'slides/')
# Enables the ability to show all slides in a tile overview by pressing 'o'
xaringanExtra::use_tile_view()
xaringanExtra::use_panelset()
xaringanExtra::use_clipboard()
xaringanExtra::use_share_again()
xaringanExtra::style_share_again(share_buttons = 'all')
xaringanExtra::use_extra_styles(
  hover_code_line = TRUE,
  mute_unhighlighted_code = FALSE
)
```

layout: true

<!-- this adds the link footer to all slides, depends on footer-small class in css-->

<div class="footer-small"><span>https://github.com/paradigmdatagroup/slide_title</span></div>

---
name: title-slide
class: title-slide, center, middle, inverse

# `r rmarkdown::metadata$title`
#.fancy[`r rmarkdown::metadata$subtitle`]

<br>

.large[by Martin Frigaard]

Written: `r dateWritten`

Updated: `r today`
